// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FunBar: typeof import('./src/components/FunBar.vue')['default']
    Header: typeof import('./src/components/Main/Header.vue')['default']
    JisAudio: typeof import('./src/components/Jis-Audio.vue')['default']
    JisInput: typeof import('./src/components/Jis-Input.vue')['default']
    Main: typeof import('./src/components/Main/main.vue')['default']
    Menu: typeof import('./src/components/Main/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
